spring.application.name=gemstore
# Server Port
server.port=8080

# SQL Server Connection
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=gemstore_db;encrypt=false
spring.datasource.username=sa
spring.datasource.password=123
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect

# File Upload Limit
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

payhere.merchantId=1234164

# Sandbox for now:
payhere.currency=LKR

app.email.enabled=true
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=harshanadeshapriyat@gmail.com
spring.mail.password=wxfh eeqh tukj jcna
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true


